export const categories = [
  { id: "all", name: "All MCPs", icon: "🏥", number: 0 },
  { id: "rcm", name: "Revenue Cycle", icon: "💰", number: 1 },
  { id: "cds", name: "Clinical Decision Support", icon: "🩺", number: 2 },
  { id: "fhir", name: "FHIR & Interoperability", icon: "🔗", number: 3 },
  { id: "quality", name: "Quality & Compliance", icon: "✅", number: 4 },
  { id: "credentialing", name: "Credentialing", icon: "🪪", number: 5 },
  { id: "medlegal", name: "Medical-Legal", icon: "⚖️", number: 6 },
  { id: "education", name: "Medical Education", icon: "📚", number: 7 },
  { id: "pophealth", name: "Population Health", icon: "📊", number: 8 },
  { id: "lifesci", name: "Life Sciences", icon: "🧬", number: 9 },
  { id: "payer", name: "Payer Operations", icon: "🏦", number: 10 },
];

export const hipaaLevels = {
  5: { badge: "HIPAA-Ready", color: "bg-emerald-500/20 text-emerald-400 border-emerald-500/30", dot: "bg-emerald-400", desc: "Full BAA, AES-256, audit logging, RBAC" },
  4: { badge: "HIPAA-Aware", color: "bg-blue-500/20 text-blue-400 border-blue-500/30", dot: "bg-blue-400", desc: "Encryption in transit, no PHI storage" },
  3: { badge: "De-identified", color: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30", dot: "bg-yellow-400", desc: "Aggregate/de-identified data only" },
  2: { badge: "Reference Only", color: "bg-slate-500/20 text-slate-300 border-slate-500/30", dot: "bg-slate-400", desc: "Public data sources only" },
  1: { badge: "Unvetted", color: "bg-slate-700/20 text-slate-500 border-slate-600/30", dot: "bg-slate-600", desc: "Not yet assessed" },
};

export const clinicalScores = {
  A: { label: "Clinically Validated", color: "text-emerald-400" },
  B: { label: "Clinically Informed", color: "text-blue-400" },
  C: { label: "Operationally Useful", color: "text-amber-400" },
  D: { label: "Experimental", color: "text-slate-400" },
};

export const mcps = [
  {
    id: "reimbursement-engine",
    name: "ReimbursementEngine",
    featured: false,
    source: "rdmgator12/reimbursement-engine",
    url: null,
    description: "18 tools covering Medicare coverage determination, ICD-10 coding, NPI validation, payer policy analysis, PubMed search, and bioRxiv/medRxiv preprint search.",
    categories: ["rcm", "credentialing", "lifesci"],
    hipaa_level: 4,
    clinical_score: "C",
    tool_count: 18,
    tools: ["search_national_coverage", "batch_get_ncds", "search_local_coverage", "sad_exclusion_list", "search_codes", "lookup_code", "validate_code", "get_hierarchy", "get_by_category", "npi_search", "npi_lookup", "npi_validate", "get_contractors", "get_whats_new_report", "search_articles", "get_article_metadata", "search_preprints", "get_preprint"],
    languages: [],
    maintainer: "Ralph Martello, MD",
  },
  {
    id: "medical-mcp",
    name: "Medical-MCP",
    featured: false,
    source: "JamesANZ/medical-mcp",
    url: "https://github.com/JamesANZ/medical-mcp",
    description: "Comprehensive medical information from FDA, WHO, PubMed, RxNorm, and Google Scholar.",
    categories: ["cds"],
    hipaa_level: 2,
    clinical_score: "B",
    tool_count: null,
    tools: [],
    languages: ["Python"],
    maintainer: "JamesANZ",
  },
  {
    id: "healthcare-data-hub",
    name: "Healthcare Data Hub",
    featured: false,
    source: "Cicatriiz/healthcare-mcp-public",
    url: "https://github.com/Cicatriiz/healthcare-mcp-public",
    description: "All-in-one: FDA drug info, PubMed, medRxiv, NCBI Bookshelf, clinical trials, ICD-10, DICOM metadata, medical calculator.",
    categories: ["cds"],
    hipaa_level: 2,
    clinical_score: "B",
    tool_count: null,
    tools: [],
    languages: ["Node.js"],
    maintainer: "Cicatriiz",
  },
  {
    id: "nice-mcp",
    name: "NICE MCP Server",
    featured: false,
    source: "awesome-medical-mcp-servers",
    url: null,
    description: "UK NICE Clinical Guidelines access via MCP. National guidelines body — clinically validated.",
    categories: ["cds"],
    hipaa_level: 2,
    clinical_score: "A",
    tool_count: null,
    tools: [],
    languages: [],
    maintainer: null,
    notes: "UK guidelines only",
  },
  {
    id: "medadapt-content-server",
    name: "MedAdapt Content Server",
    featured: false,
    source: "ryoureddy/medadapt-content-server",
    url: "https://github.com/ryoureddy/medadapt-content-server",
    description: "AI-assisted medical learning with adaptive content from PubMed, NCBI Bookshelf, and user documents.",
    categories: ["cds", "education"],
    hipaa_level: 2,
    clinical_score: "B",
    tool_count: null,
    tools: [],
    languages: ["Python"],
    maintainer: "ryoureddy",
  },
  {
    id: "biothings-mcp",
    name: "BioThings MCP",
    featured: false,
    source: "longevity-genie/biothings-mcp",
    url: "https://github.com/longevity-genie/biothings-mcp",
    description: "Query genes, genetic variants, drugs, and taxonomic information via the BioThings API.",
    categories: ["cds", "lifesci"],
    hipaa_level: 2,
    clinical_score: "B",
    tool_count: null,
    tools: [],
    languages: ["Python"],
    maintainer: "longevity-genie",
  },
  {
    id: "wso2-fhir-mcp",
    name: "WSO2 FHIR MCP Server",
    featured: true,
    source: "wso2/fhir-mcp-server",
    url: "https://github.com/wso2/fhir-mcp-server",
    description: "Expose any FHIR Server or API as an MCP Server. SMART-on-FHIR authentication. Full CRUD on FHIR resources. Direct CMS-0057 relevance.",
    categories: ["fhir"],
    hipaa_level: 4,
    clinical_score: "B",
    tool_count: null,
    tools: [],
    languages: ["TypeScript"],
    maintainer: "WSO2",
  },
  {
    id: "momentum-fhir-mcp",
    name: "Momentum FHIR MCP",
    featured: false,
    source: "the-momentum/fhir-mcp-server",
    url: "https://github.com/the-momentum/fhir-mcp-server",
    description: "Natural language interface for healthcare data. Eliminates weeks of FHIR learning. Prevents LLM hallucination of medical codes.",
    categories: ["fhir"],
    hipaa_level: 4,
    clinical_score: "B",
    tool_count: null,
    tools: [],
    languages: ["TypeScript"],
    maintainer: "The Momentum",
  },
  {
    id: "aws-healthlake-mcp",
    name: "AWS HealthLake MCP",
    featured: false,
    source: "awslabs/mcp",
    url: "https://awslabs.github.io/mcp/servers/healthlake-mcp-server",
    description: "MCP server for AWS HealthLake FHIR operations. 11 tools for FHIR resource management with automatic datastore discovery.",
    categories: ["fhir"],
    hipaa_level: 5,
    clinical_score: "B",
    tool_count: 11,
    tools: [],
    languages: ["Python"],
    maintainer: "AWS Labs",
    notes: "Requires AWS account with HealthLake",
  },
  {
    id: "flexpa-fhir-mcp",
    name: "Flexpa FHIR MCP",
    featured: false,
    source: "flexpa/mcp-fhir",
    url: "https://github.com/flexpa/mcp-fhir",
    description: "Connect to health plans and retrieve patient claims, coverage, and clinical data via FHIR.",
    categories: ["fhir"],
    hipaa_level: 4,
    clinical_score: "C",
    tool_count: null,
    tools: [],
    languages: ["TypeScript"],
    maintainer: "Flexpa",
  },
  {
    id: "health-record-mcp",
    name: "Health Record MCP",
    featured: false,
    source: "jmandel/health-record-mcp",
    url: "https://github.com/jmandel/health-record-mcp",
    description: "Connect to an EHR and make clinical data available via MCP. By Josh Mandel (former SMART Health IT lead).",
    categories: ["fhir"],
    hipaa_level: 4,
    clinical_score: "A",
    tool_count: null,
    tools: [],
    languages: ["TypeScript"],
    maintainer: "Josh Mandel",
  },
  {
    id: "agentcare-mcp",
    name: "AgentCare MCP",
    featured: false,
    source: "Kartha-AI/agentcare-mcp",
    url: "https://github.com/Kartha-AI/agentcare-mcp",
    description: "Healthcare tools and prompts for interacting with FHIR data on EMRs like Cerner and Epic.",
    categories: ["fhir"],
    hipaa_level: 4,
    clinical_score: "B",
    tool_count: null,
    tools: [],
    languages: ["TypeScript"],
    maintainer: "Kartha-AI",
  },
  {
    id: "dicom-mcp",
    name: "DICOM MCP Server",
    featured: false,
    source: "ChristianHinge/dicom-mcp",
    url: "https://github.com/ChristianHinge/dicom-mcp",
    description: "Query, read, and move medical images and reports from PACS and other DICOM-compliant systems.",
    categories: ["fhir"],
    hipaa_level: 3,
    clinical_score: "B",
    tool_count: null,
    tools: [],
    languages: ["Python"],
    maintainer: "ChristianHinge",
  },
  {
    id: "innovaccer-hmcp",
    name: "Innovaccer HMCP",
    featured: false,
    source: "innovaccer/Healthcare-MCP",
    url: "https://github.com/innovaccer/Healthcare-MCP",
    description: "Specialized MCP extension with HIPAA guardrails, OAuth2, audit trails, and compliance layer. Enterprise-grade.",
    categories: ["quality"],
    hipaa_level: 5,
    clinical_score: "C",
    tool_count: null,
    tools: [],
    languages: [],
    maintainer: "Innovaccer",
    notes: "Enterprise product — requires licensing",
  },
  {
    id: "pubmed-standalone",
    name: "Standalone PubMed MCP",
    featured: false,
    source: "rikachu225/mcp-pubmed-server",
    url: "https://github.com/rikachu225/mcp-pubmed-server",
    description: "Standalone PubMed search MCP server for biomedical literature access.",
    categories: ["lifesci"],
    hipaa_level: 2,
    clinical_score: "A",
    tool_count: null,
    tools: [],
    languages: [],
    maintainer: "rikachu225",
  },
  {
    id: "protein-structure-analyzer",
    name: "Protein Structure Analyzer",
    featured: false,
    source: "awesome-medical-mcp-servers",
    url: null,
    description: "Protein structure analysis via MCP for research and drug discovery workflows.",
    categories: ["lifesci"],
    hipaa_level: 2,
    clinical_score: "D",
    tool_count: null,
    tools: [],
    languages: [],
    maintainer: null,
  },
  {
    id: "3d-slicer-mcp",
    name: "3D Slicer MCP",
    featured: false,
    source: "awesome-medical-mcp-servers",
    url: null,
    description: "3D Slicer medical imaging integration via MCP for radiology and surgical planning.",
    categories: ["lifesci"],
    hipaa_level: 3,
    clinical_score: "B",
    tool_count: null,
    tools: [],
    languages: [],
    maintainer: null,
    notes: "Requires 3D Slicer installation",
  },
  {
    id: "apple-health-mcp",
    name: "Apple Health MCP",
    featured: false,
    source: "the-momentum/apple-health-mcp-server",
    url: "https://github.com/the-momentum/apple-health-mcp-server",
    description: "Access exported Apple Health data with built-in analytics for population health workflows.",
    categories: ["pophealth"],
    hipaa_level: 3,
    clinical_score: "D",
    tool_count: null,
    tools: [],
    languages: [],
    maintainer: "The Momentum",
  },
];

export const bundles = [
  {
    id: "denial-fighter",
    name: "Denial Fighter",
    icon: "🔥",
    description: "Analyze, appeal, and prevent claim denials",
    mcps: ["reimbursement-engine", "pubmed-standalone"],
    tags: ["NCD/LCD Lookup", "ICD-10 Validation", "Clinical Evidence", "NPI Verification"],
  },
  {
    id: "prior-auth-stack",
    name: "Prior Auth Stack",
    icon: "🔥",
    description: "CMS-0057 aligned prior authorization workflow",
    mcps: ["reimbursement-engine", "wso2-fhir-mcp"],
    tags: ["Coverage Determination", "FHIR Submission", "Medical Necessity", "Coding Accuracy"],
  },
  {
    id: "clinical-reference-kit",
    name: "Clinical Reference Kit",
    icon: "🔥",
    description: "Point-of-care reference tools for clinicians",
    mcps: ["medical-mcp", "healthcare-data-hub", "biothings-mcp"],
    tags: ["Drug Info", "Interactions", "Literature Search", "Genomics"],
  },
  {
    id: "fhir-interop-suite",
    name: "FHIR Interop Suite",
    icon: "🔥",
    description: "Complete FHIR toolkit for CMS-0057/HTI-1 compliance",
    mcps: ["wso2-fhir-mcp", "momentum-fhir-mcp", "health-record-mcp", "agentcare-mcp", "dicom-mcp"],
    tags: ["SMART-on-FHIR", "EHR Integration", "DICOM", "Natural Language"],
  },
  {
    id: "compliance-suite",
    name: "Compliance Suite",
    icon: "🔥",
    description: "Quality reporting and regulatory compliance",
    mcps: ["reimbursement-engine", "innovaccer-hmcp"],
    tags: ["Medicare Policy", "HIPAA", "Credentialing", "Audit Trails"],
  },
];

export const stats = {
  totalMcps: 18,
  totalTools: "60+",
  totalCategories: 10,
  hipaaRated: "100%",
};
